### ISSUE TITLE
创建个datasets文件夹吧

### ISSUE THREAD

**Issue by wengJJ** [MachineLearning100/100-Days-Of-ML-Code#14]
像原作者那样

**Comment by yyong119** [comment]
确实那样更好。<br>
如果要做的话赶紧了，等python文件多起来后，要去改所有python文件中读取dataset的路径会是很繁琐的事情，建议现在用1个commit把所有的data和python文件全部搞定。

**Comment by zhyongquan** [comment]
ok，已添加

**Comment by wengJJ** [comment]
现在有datasets文件夹了 各位上传完整代码 可以的话 尽量写成这种格式
读取数据：
dataset = pd.read_csv('../datasets/XXX.csv')
