### ISSUE TITLE
中文规范

### ISSUE THREAD

**Issue by zhyongquan** [MachineLearning100/100-Days-Of-ML-Code#18]
是不是定一些规范，比如：
1.标题要不要翻译成中文
2.天数是写阿拉伯数字还是汉字等？
统一一下，更美观。

**Comment by yyong119** [comment]
建议标题 ：支持向量机（SVM）、逻辑回归（Logistic Regression） etc.
建议天数全部更改为阿拉伯数字

**Comment by zhyongquan** [comment]
ok
1.标题保留英文会更好找
2.天数如果后面到了几十天以上，阿拉伯数字更清晰
那图片最上面#100DaysOfMLCode要翻译吗？

**Comment by yyong119** [comment]
> 那图片最上面#100DaysOfMLCode要翻译吗？

个人感觉这个不翻译和repo名字保持相近更好。

**Comment by wengJJ** [comment]
现在是标题都要保留原英文吗

**Comment by zhyongquan** [comment]
markdown和notebook文件中经常用到step xxx，翻译成哪种呢？
1.第1步，第2步
2.第一步，第二步
3.步骤1，步骤2
4.步骤一，步骤二

**Comment by goelo** [comment]
我选3

发自网易邮箱 iPhone 版
在2018年08月07日 12:26，zhang yongquan 写道:

markdown和notebook文件中经常用到step xxx，翻译成哪种呢？
1.第1步，第2步
2.第一步，第二步
3.步骤1，步骤2
4.步骤一，步骤二

**Comment by Aaaaaaada** [comment]
我选1

**Comment by wengJJ** [comment]
我选2 
个人意见：原作者标题100DaysOfMLCode不改 因为这才是原版的 下面的部分还是翻译成中文就好

**Comment by zhyongquan** [comment]
OK。选哪个的都有啊，😄

**Comment by yyong119** [comment]
jupyter notebook中现有的3份已经是第2种了，我觉得就继续下去吧😂

**Comment by Great1414** [comment]
![default](https://user-images.githubusercontent.com/34801728/43869516-7b4d1d76-9ba5-11e8-887e-81dde987d390.png)
大家没必要太纠结这个事吧。 @zhyongquan 根据大家想法，做个统一，大家跟随，觉得怎么样，哈哈

**Comment by Great1414** [comment]
我的意思是，后续还会有翻译。 @zhyongquan ，根据大家的意见，和实际情况，反馈。做个统一要求，大家跟着就行了。

**Comment by zhyongquan** [comment]
@MachineLearning100/translator 结合最近碰到的问题，暂定如下
## 翻译规范`v20180809`
### 交付物
>- 图片（.jpg），质量选择最高，源文件自己保留好，文件命名`Day xxx.jpg`
>- 代码，含md、py、notebook等，要求调试通过，数据引用datasets文件夹`../datasets/xxxx.csv`，文件命名`Day xxx_xxxx_xxxx.md`
### 忽略区域
>- 页眉（`#100DaysOfMLCode`+`Day XXX`+`@Avik Jain`）
>- 页脚（`github`+`Follow`）
>- 图表坐标轴
>- 代码，如库、类、方法名称等
### 强制区域
>-  图表说明文字
### 格式
>- 字体颜色、间距等格式和原文保持一致。
### 数字
>- 需要用到数字编号的，一律使用阿拉伯数字`1234567890`，如：`步骤1`，`步骤2`等
>- 文字内容中，从中文习惯出发，使用`二维`、`三维`、`两个`等
### 符号
>- 编号等使用英文符号，如`1.`，`2.`等
>- 除特殊要求外，其他都用中文符号，如`，`，`。`，`：`，`？`等
### 保留英文场景
>- 标题或正文中，如果英文认知度更高，更准确，则翻译成`中(英)`。注意使用了**英文括号**。
