### ISSUE TITLE
目录

### ISSUE THREAD

**Issue by zhyongquan** [MachineLearning100/100-Days-Of-ML-Code#24]
想给readme加个目录，没成功，看看哪里有问题?

**Comment by wengJJ** [comment]
路径可以这样写吗 没试过 要不你就按下面那种URL路径去写就最安全了

**Comment by zhyongquan** [comment]
可以链接到下面的标题，不知道为什么不行

**Comment by wengJJ** [comment]
个人感觉应该是中间分隔符的问题
你写的目录URL：.../#数据预处理-%7C-第1天
手动点击标题的URL：.../#数据预处理--第1天

**Comment by zhyongquan** [comment]
你说得对，竖线居然不认识，删掉后就好了
