### ISSUE TITLE
day33 随机森林

### ISSUE THREAD

**Issue by zhyongquan** [MachineLearning100/100-Days-Of-ML-Code#30]
谁没翻译过?来参与一下。

**Comment by AnnaXJGe** [comment]
我翻译吧

**Comment by zhyongquan** [comment]
可以，之后作者还会写个MD文件，也一起翻译了

**Comment by zhyongquan** [comment]
标题增加一个树的阴影，做了个效果，抛砖引玉
![image](https://user-images.githubusercontent.com/11530247/43835964-5cb3187a-9b46-11e8-86f6-c0663c3b3fc0.png)

**Comment by AnnaXJGe** [comment]
谢谢！

**Comment by zhyongquan** [comment]
没有原作者的好看，哈哈

**Comment by zhyongquan** [comment]
有几个问题
1. 图片质量是不是最高，放大后有点糊?只有300多kb
2. “决策森林”应该是“随机森林”吧
3. 白色字体和黄色背景看不太清，字体加粗了吗？

**Comment by AnnaXJGe** [comment]
我改下

**Comment by zhyongquan** [comment]
有个地方写的随机林，少了个森

**Comment by zhyongquan** [comment]
1. 标题里random少了个n，我写错了
2. md文件已更新，翻译一下

**Comment by zhyongquan** [comment]
在搬运错误里还有其他几个问题，一起改了

**Comment by AnnaXJGe** [comment]
好的

**Comment by zhyongquan** [comment]
1. 根据要求，md文件名里的第二个空格要改成下划线，
2. 数据路径名改成datasets文件夹里的
3. 原作里没加输出的结果图片，在Python里试一下，我们把图片加上

**Comment by AnnaXJGe** [comment]
谢谢！标题和输出图片已更新，关于数据集路径，我不太明白你的意思~

**Comment by zhyongquan** [comment]
1. 现在数据写的csv文件名，所以要把代码和数据放到一个文件夹，而实际数据在datasets文件夹，应该加上路径名
2 结果的图片放到other docs文件夹
3. ipynb文件打开不对，显示成了纯文本，看看哪里有问题
