### ISSUE TITLE
关于工作方案

### ISSUE THREAD

**Issue by yyong119** [MachineLearning100/100-Days-Of-ML-Code#39]
现在我把之前的那些python文件都补全了。

- 建议之后在翻译md文件后，把py和ipynb文件一并上传(这样一次性的工作量比较大，一人每次间隔交大)。
- 或者按次序一个人md中的文本翻译，一个人的话翻译图片内容，一个人python文件，一个人jupyter notebook 文件(这样每个人每次工作量较小)。

两种方案各位怎么看？

**Comment by wengJJ** [comment]
我觉得方案一吧 负责一个算法就全部都包办吧 这样才不会出现上下文翻译不一致的问题

**Comment by zhyongquan** [comment]
就按第一个吧，目前我在规范里也这样要求的，作者的图片和代码也不是一天完成的，有时间去翻译

**Comment by goelo** [comment]
现在还有遗留的task吗？老板


发自网易邮箱 iPhone 版
在2018年08月11日 17:04，zhang yongquan 写道:

就按第一个吧，目前我在规范里也这样要求的，作者的图片和代码也不是一天完成的，有时间去翻译

**Comment by yyong119** [comment]
现在已经跟上英文repo的进度了 @goelo

**Comment by goelo** [comment]
嗯呀。好的吧


发自网易邮箱 iPhone 版
在2018年08月11日 19:13，Yong Mao 写道:

现在已经跟上英文repo的进度了 @goelo
