### ISSUE TITLE
“拆分数据”和“特征缩放”的顺序

### ISSUE THREAD

**Issue by zhyongquan** [MachineLearning100/100-Days-Of-ML-Code#41]
刚看到有人提出这个问题：`特征缩放`要放在`拆分数据`之前。我觉得挺有道理，这样才能保证拆分后的`训练集合`和`测试集合`一致。

**Comment by wengJJ** [comment]
之前回答过英文版的问题，还是保持原来的观点-先拆分数据再特征缩放。
常用的特征缩放：**归一化（Normalization）**与**标准化（Standardization）**
**归一化Normalization=(x-min)/(max-min)**涉及样本的**极大极小值**，
**标准化Standardization=(x-μ)/(σ)**涉及样本的**均值μ**与**标准差σ**
先进行总体特征缩放，例如归一化的极大值max存在于测试集，这就会让测试集的数据影响到训练集的数据，而我们划分训练集测试集的原则就是**彼此不受干扰**，保证得出模型的效果准确性。
所以，个人观点还是得先拆分数据再特征缩放

**Comment by zhyongquan** [comment]
我的理解，如果数据量足够大，先后都无所谓，但当数据不够多时，影响会变大。

**Comment by zhyongquan** [comment]
哪个文件？

**Comment by Huang-Jack** [comment]
day6 @zhyongquan

**Comment by Huang-Jack** [comment]
我试了都改成 fit_transform不会报错了，但是我不知道他们的区别是什么

**Comment by zhyongquan** [comment]
摘自此文章的评论https://blog.csdn.net/appleyuchi/article/details/73503282
我觉得讲的比正文更清楚
**每一个transform都需要先fit,比如把数据转为（0，1）分布，需要均值和标准差，fit_transform和transform的区别就是前者是先计算均值和标准差再转换，而直接transform则是用之前数据计算的参数转换。所以如果之前没有fit，是不能直接transform的。**
在此例子中，前文已经用过一个fit_transform了，后面用fit_transform或transform都可以，因为已经fit过了。作者的用意是不是要用训练集合的fit参数，去transform测试集和？以此达到两者相同的变化。

**Comment by zhyongquan** [comment]
@wengJJ 
本issue讨论的顺序问题，作者在transform时考虑了？

**Comment by zhyongquan** [comment]
所以train和test的transform，要使用同样的fit参数

**Comment by wengJJ** [comment]
进行特征缩放时我们的顺序是 
1先fit获得相应的参数值（可以理解为获得特征缩放规则） 2再用transform进行转换
fit_transform方法就是先执行fit()方法再执行transform()方法，所以每执行一次就会采用新的特征缩放规则

@Huang-Jack 你提出的说测试集使用fit_transform效果变差是肯定的，因为你使用的是**测试集**的新的规则来进行转换。如果你使用的是transform，则会使用**训练集**的规则进行转换，效果会更好。
@zhyongquan 顺序问题还是不会冲突 作者是用训练集的特征缩放规则来应用到测试集的，所以还是先得先拆分数据集 再进行特征缩放

**Comment by zhyongquan** [comment]
是的，这个issue算讨论明白了。
