### ISSUE TITLE
tensorflow实现

### ISSUE THREAD

**Issue by zhyongquan** [MachineLearning100/100-Days-Of-ML-Code#42]
tensorflow是当下最流行的库，是否有必要把所有例子用tensorflow实现一遍？

**Comment by yyong119** [comment]
建议先看原作者会不会在之后加入tf的学习内容
因为之前我自学是跟着coursera上的deeplearning.ai的课程的，Andrew NG在恰当的地方（大概是代码复杂度突然上升的地方）引入了tf，之后就一直不是原始代码了，所以我觉得也许我们可以先等一等，后续代码复杂了原作者也不一定会自己去写bp之类的而是直接使用tf了
