### ISSUE TITLE
Day 2

### ISSUE THREAD

**Issue by zhyongquan** [MachineLearning100/100-Days-Of-ML-Code#5]
@wengJJ 
我试过Day 2的代码，在pycharm中，可视化时，如果不添加下面代码，不能弹出绘图窗口。
 ```python
plt.show()
 ```

**Comment by wengJJ** [comment]
我记得以前好像mac上可以不用plt.show()也可以显示，不过这个是个新手教程，我还是加上吧

**Comment by zhyongquan** [comment]
要不完整的代码也放一份？

**Comment by wengJJ** [comment]
我个人觉得原作者这个代码已经可以运行了 没必要再放一份

**Comment by zhyongquan** [comment]
ok

**Comment by wengJJ** [comment]
我觉得看吧 目前这些例子还是挺简单的 后期如果有复杂的 感觉就可以把完整代码放上

**Comment by Aaaaaaada** [comment]
jupyter book上，不加plt.show()是可以运行的

**Comment by yyong119** [comment]
我来上传jupyter notebook的吧
