### ISSUE TITLE
深度学习基础Python，TensorFlow和Keras 课程会在b站有双语视频吗

### ISSUE THREAD

**Issue by SmallSir** [MachineLearning100/100-Days-Of-ML-Code#52]
我想问一下，深度学习基础Python部分的视频b站会有双语的嘛

**Comment by zhyongquan** [comment]
我没找到，只找到这个https://pythonprogramming.net/introduction-deep-learning-python-tensorflow-keras/

**Comment by yyong119** [comment]
那我有空把他翻译一下吧，需要另外新建repo吗？还是多个文件夹直接添加上去？

**Comment by zhyongquan** [comment]
直接放在code里行吗?命名成Day xxx.ipynb，readme里加个链接

**Comment by zhyongquan** [comment]
没必要全文翻译过来，挑重点，对初学者重要的信息，比如pip安装，数据下载之类的

**Comment by zhyongquan** [comment]
我安装的tf 1.10老是出错

```
pip install --upgrade tensorflow
```

后来到tf github看到tf-nightly，倒是可以

```
pip install tf-nightly
```

**Comment by yyong119** [comment]
好的，我准备开始翻译了，那个安装的我都写上去好了

**Comment by zhyongquan** [comment]
要不你看下后面的，第一页我做好了

**Comment by yyong119** [comment]
那么你先上传吧，我按照第一页的模板来做好了，这样格式可以统一点

**Comment by zhyongquan** [comment]
https://github.com/MachineLearning100/100-Days-Of-ML-Code/blob/master/Code/Day%2039.ipynb

**Comment by yyong119** [comment]
好，那我开始翻译Day 40的了

**Comment by yyong119** [comment]
更新Day41&42中，预计今天能全部翻译完

**Comment by zhyongquan** [comment]
已完成
